from fastapi import FastAPI, Depends
from fastapi.middleware.cors import CORSMiddleware
from sqlalchemy.orm import Session
import models
from database import engine, SessionLocal
from pydantic import BaseModel, ConfigDict
from typing import List, Optional

models.Base.metadata.create_all(bind=engine)

app = FastAPI(title="TruthLens AI Backend")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

def get_db():
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()

# Pydantic schemas
class UserCreate(BaseModel):
    username: str

class UserResponse(BaseModel):
    id: int
    username: str
    score: int
    level: int
    xp: int

    model_config = ConfigDict(from_attributes=True)

class QuestionResponse(BaseModel):
    id: int
    type: str
    content_url: Optional[str] = None
    text_content: Optional[str] = None
    is_ai: Optional[int] = None
    options: Optional[str] = None
    correct_option: Optional[int] = None
    explanation: str
    difficulty: str
    category: Optional[str] = None

    model_config = ConfigDict(from_attributes=True)

@app.get("/")
def read_root():
    return {"message": "Welcome to TruthLens AI"}

@app.get("/questions/", response_model=List[QuestionResponse])
def get_questions(db: Session = Depends(get_db)):
    return db.query(models.Question).all()

@app.get("/leaderboard/", response_model=List[UserResponse])
def get_leaderboard(db: Session = Depends(get_db)):
    return db.query(models.User).order_by(models.User.score.desc()).limit(10).all()

class ScoreSubmission(BaseModel):
    username: str
    score: int
    level: int = 1
    xp: int = 0

@app.post("/leaderboard/")
def submit_score(submission: ScoreSubmission, db: Session = Depends(get_db)):
    # Check if user exists
    user = db.query(models.User).filter(models.User.username == submission.username).first()
    if user:
        if submission.score > user.score:
            user.score = submission.score
            user.xp += submission.score
            user.level = (user.xp // 1000) + 1
    else:
        user = models.User(
            username=submission.username, 
            score=submission.score,
            xp=submission.score,
            level=(submission.score // 1000) + 1
        )
        db.add(user)
    db.commit()
    return {"message": "Score saved successfully!"}

# Add a route to populate sample data
@app.post("/populate_sample_data/")
def populate_data(db: Session = Depends(get_db)):
    if db.query(models.Question).count() == 0:
        samples = [
            models.Question(
                type="image",
                content_url="https://images.unsplash.com/photo-1549692520-acc6669e2f0c?q=80&w=2787&auto=format&fit=crop",
                is_ai=0,
                explanation="This is a real photograph. Notice the consistent lighting, natural skin texture, and physically accurate background elements.",
                difficulty="easy",
                category="General"
            ),
            models.Question(
                type="image",
                content_url="https://images.nightcafe.studio/jobs/HkGv4rM8bXl8YJ42JbFj/HkGv4rM8bXl8YJ42JbFj--1--p8g6u.jpg",
                is_ai=1,
                explanation="This is AI generated. Look closely at the hands/fingers, unnatural blending of objects in the background, and hyper-smooth skin textures.",
                difficulty="medium",
                category="General"
            ),
            models.Question(
                type="text",
                text_content="The rapid advancement of artificial intelligence has led to numerous breakthroughs in various fields. From natural language processing to computer vision, AI systems are becoming increasingly capable. However, it is crucial to consider the ethical implications of these technologies. As AI continues to evolve, we must ensure that it is developed and deployed responsibly, prioritizing human values and mitigating potential risks.",
                is_ai=1,
                explanation="This text exhibits common AI patterns: repetitive structure, broad generalizations without specific examples, and predictable transitions.",
                difficulty="easy",
                category="General"
            ),
             models.Question(
                type="code",
                text_content="def calculate_fibonacci(n):\n    if n <= 0:\n        return []\n    elif n == 1:\n        return [0]\n    sequence = [0, 1]\n    while len(sequence) < n:\n        next_val = sequence[-1] + sequence[-2]\n        sequence.append(next_val)\n    return sequence\n\n# Calculate first 10 Fibonacci numbers\nprint(calculate_fibonacci(10))",
                is_ai=1,
                explanation="While perfectly functional, this code represents a textbook algorithm implementation commonly generated by AI, lacking any specific business logic or contextual variable names.",
                difficulty="hard",
                category="Programming"
            )
        ]
        db.add_all(samples)
        db.commit()
        return {"message": "Sample data populated"}
    return {"message": "Data already exists"}

if __name__ == "__main__":
    import uvicorn
    uvicorn.run("main:app", host="0.0.0.0", port=8000, reload=True)
